baseURL: 'https://drornir.dev/'
languageCode: 'en-us'
title: 'drornir.dev'
theme: PaperMod

params: # https://github.com/adityatelange/hugo-PaperMod/wiki/Features

  defaultTheme: dark
  disableThemeToggle: false

  profileMode:
    enabled: true
    imageUrl: ./profile.png
    title: I'm dror
    subtitle: Go Developer, making Dev Platforms with DevOps practices üê≥
    buttons:
      - name: Blog
        url: /posts

  socialIcons:
    - name: github
      url: https://github.com/drornir
    - name: email
      url: mailto:dror.nir0@gmail.com
    - name: twitter
      url: https://twitter.com/drornir
    - name: linkedin
      url: https://www.linkedin.com/in/dror-nir-5b49a159/

#deployment:
#  targets:
#    - name: gcs
#      URL: gs://drornir.dev
#  matchers:
#    - pattern: ^.+\.(js|css|svg|ttf)$
#      cacheControl: max-age=31536000, no-transform, public
#      gzip: true
#    - pattern: ^.+\.(png|jpg)$
#      cacheControl: max-age=31536000, no-transform, public
#      gzip: false
#    - pattern: ^sitemap\.xml$
#      contentType: application/xml
#      gzip: true
#    - pattern: ^.+\.(html|xml|json)$
#      gzip: true
